---
title: "Corpus analysis"
subtitle: "Exploration of frequency of terms in President Obrador's speeches"
author: "Marco Schildt, Santiago Sordo, Gülce Sena Tuncer"
output: 
  html_document:
    toc: TRUE
    df_print: paged
    number_sections: FALSE
    highlight: monochrome
    theme: darkly
    toc_depth: 3
    toc_float: true
    css: custom.css 
    self_contained: false
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits=2)
```

## R Markdown

```{r, message=F, comment=F}
mydir = "speeches"
txtfiles = list.files(path=mydir, pattern="*.txt", full.names=TRUE)
head(txtfiles)
tail(txtfiles)
```



```{r, message=F, comment=F}
library(tidyr)
library(stringr)
library(dplyr)

parse_amlo <- function(file) {
  
  date <- substring(file, 10,19)
  try({
    speech <- readChar(file, file.info(file)$size)

    # This is the pattern that so far returns the speakers correctly
    pattern <- "([ A-ZÀ-Ú])+:"
    
    # Those were examples, now do this for the whole file to prep the speech for splitting
    prepped_speech <- str_replace_all(speech, pattern, "##\\0##")
    
    # This splits it row by row, but of course we need speaker and speech on the same column
    parsed_speech <- as.data.frame(str_split(prepped_speech, "##"), col.names = "A")
    
    parsed_speech <- parsed_speech %>%
      tail(-1)%>%  # remove first row  which has no speaker
      mutate(variable = rep(c("Speaker", "Text"), nrow(parsed_speech) / 2), 
           key = rep(1:(nrow(parsed_speech) / 2), each = 2)) %>%
      pivot_wider(id_cols = key, names_from = variable, values_from = A) %>% # divide speaker and text in separate columns 
      select(-key) %>% # remove helper 
      group_by(Speaker) %>% 
      summarize(Text = paste(Text, collapse = " ")) %>% # combine text of each speaker 
      mutate(Date = date, .before = Speaker)
    
    
    })
  
  return(parsed_speech)
  
  }

#test <- parse_amlo(txtfiles[1])
```


```{r, message=F, comment=F}
# creates list
sample = lapply(txtfiles, parse_amlo)
# create data frame
sample_df <- do.call(rbind,lapply(txtfiles, parse_amlo))
# write csv from data frame
write.csv(sample_df,"sample_df.csv")

```


```{r, message=F, comment=F}
#load the df from the CSV
sample_df2 <- read.csv(file = 'sample_df.csv', header = TRUE)%>%  
      select(-X)
```

##Creating corpuses for data analysis

```{r, message=F, comment=F}
#create corpus with quanteda
library("quanteda")
main_corpus <- corpus(sample_df2, text_field = "Text")
summary(main_corpus)

#create corpus with "Month" grouping
docvars(main_corpus, field = "Month") <- substring(docvars(main_corpus, field = "Date"), 1,7)
```

##Preparing tokens and subsets

```{r, message=F, comment=F}
#clean and create tokens for main corpus
main_tokens <- tokens(main_corpus, remove_punct = TRUE, remove_numbers = TRUE)
main_tokens <- tokens_select(main_tokens, stopwords('spanish'), selection='remove')
main_tokens_dfm <- dfm(main_tokens)
topfeatures(main_tokens_dfm, 50)
```


```{r, message=F, comment=F}
#subsets with main corpus
#subset for president's speeches - 590 docs
subset_president <- (corpus_subset(main_corpus, Speaker == "PRESIDENTE ANDRÉS MANUEL LÓPEZ OBRADOR:"))

#subset for 2020 and 2021 - 370 docs
subset_president_interim <- (corpus_subset(subset_president, Date > "2019-12-31"))

#subset for 2020 - 223 docs
subset_president_2020 <- (corpus_subset(subset_president_interim, Date < "2021-01-01"))
summary(subset_president_2020)

#subset for 2021 - 147 docs
subset_president_2021 <- (corpus_subset(subset_president, Date > "2020-12-31"))
summary(subset_president_2021)
```

## 1) Analysis of top features in President Obrador's speeches

```{r, message=F, comment=F}
library("quanteda.textmodels")
library("quanteda.textstats")
library("quanteda.textplots")
library("ggplot2")

#tokens and df for 2020
tokens_president_2020 <- tokens(subset_president_2020, remove_punct = TRUE, remove_numbers = TRUE)
tokens_president_2020 <- tokens_select(tokens_president_2020, stopwords('spanish'), selection='remove')
tokens_president_2020 <- tokens_tolower(tokens_president_2020)
dfm_president_2020 <- dfm(tokens_president_2020)

#tokens and df for 2021
tokens_president_2021 <- tokens(subset_president_2021, remove_punct = TRUE, remove_numbers = TRUE)
tokens_president_2021 <- tokens_select(tokens_president_2021, stopwords('spanish'), selection='remove')
tokens_president_2021 <- tokens_tolower(tokens_president_2021)
dfm_president_2021 <- dfm(tokens_president_2021)

```

```{r, message=F, comment=F}
#top features frequency plots 
topfeatures(dfm_president_2020, 50)
dfm_features <- textstat_frequency(dfm_president_2020, n = 50)

dfm_features$feature <- with(dfm_features, reorder(feature, -frequency))

ggplot(dfm_features, aes(x = feature, y = frequency)) +
    geom_point() + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    labs(title = "Top Features of President Obrador's Speeches in 2020",
        y = "Frequency", x = "Feature") +
    theme(plot.title = element_text(size = 12, face = "bold", margin = margin(0, 0, 10, 0)),
        plot.subtitle = element_text(size = 10, color = "azure4", margin = margin(0, 0, 10, 0)),
        plot.caption = element_text(size = 7, color = "azure4", vjust = -2),
        axis.title.x = element_text(size = 8, color = "azure4", vjust = -2),
        axis.title.y = element_text(size = 8, color = "azure4" , vjust = 2))

topfeatures(dfm_president_2021, 50)
dfm_features_2 <- textstat_frequency(dfm_president_2021, n = 50)

dfm_features_2$feature <- with(dfm_features_2, reorder(feature, -frequency))

ggplot(dfm_features_2, aes(x = feature, y = frequency)) +
    geom_point() + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    labs(title = "Top Features of President Obrador's Speeches in 2021",
        y = "Frequency", x = "Feature") +
    theme(plot.title = element_text(size = 12, face = "bold", margin = margin(0, 0, 10, 0)),
        plot.subtitle = element_text(size = 10, color = "azure4", margin = margin(0, 0, 10, 0)),
        plot.caption = element_text(size = 7, color = "azure4", vjust = -2),
        axis.title.x = element_text(size = 8, color = "azure4", vjust = -2),
        axis.title.y = element_text(size = 8, color = "azure4" , vjust = 2))
```

## 2) Lexical dispersion analysis of covid related terms by month

```{r, message=F, comment=F}
#group by month
grouped_corpus <- corpus_group(subset_president_interim, groups = Month)
summary(grouped_corpus)
```

```{r}
#plot lexical dispersions

textplot_xray(
     kwic(grouped_corpus, pattern = "pandemia"),
     kwic(grouped_corpus, pattern = "virus"),
     kwic(grouped_corpus, pattern = "covid"),
     kwic(grouped_corpus, pattern = "crisis"),
     kwic(grouped_corpus, pattern = "sanitaria"),
     kwic(grouped_corpus, pattern = "enfermedad")
) +
  aes(color = keyword) + 
    scale_color_manual(values = c("blue", "purple", "pink", "red", "green", "yellow")) +
    theme(legend.position = "none")
```

```{r, message=F, comment=F}
#NOTE: I KEPT THIS SECTION SO THAT WE CAN TRY DIFFERENT/MORE RELEVANT KEYWORDS AND ADJUST BOTH THE LEXICAL DISPERSION PLOTS AND THE ANALYSIS WITH NEW COVID CASES

#covid related freq plots
freq_interim <- subset_president_interim %>% tokens(groups = subset_president_interim$Date) %>% dfm() %>% textstat_frequency()

# filter the terms
freq_pandemia <- subset(freq_interim, freq_interim$feature %in% "pandemia")
freq_virus <- subset(freq_interim, freq_interim$feature %in% "virus")
freq_covid <- subset(freq_interim, freq_interim$feature %in% "covid")
freq_crisis <- subset(freq_interim, freq_interim$feature %in% "crisis")
freq_sanitaria <- subset(freq_interim, freq_interim$feature %in% "sanitaria")
freq_enfermedad <- subset(freq_interim, freq_interim$feature %in% "enfermedad")

freq_plot <- rbind(freq_pandemia, freq_virus, freq_covid, freq_sanitaria, freq_enfermedad)

freq_plot$feature <- with(freq_plot, reorder(feature, -frequency))

freq_plot

ggplot(freq_plot, aes(x = feature, y = frequency)) +
    geom_point() + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    labs(title = "COVID-19 Pandemic Related Features",
         subtitle = "2020-2021",
        y = "Frequency", x = "Feature") +
    theme(plot.title = element_text(size = 12, face = "bold", margin = margin(0, 0, 8, 0)),
        plot.subtitle = element_text(size = 10, color = "azure4", margin = margin(0, 0, 10, 0)),
        plot.caption = element_text(size = 7, color = "azure4", vjust = -2),
        axis.title.x = element_text(size = 8, color = "azure4", vjust = -2),
        axis.title.y = element_text(size = 8, color = "azure4" , vjust = 2))

```

## 3) President Obrador's covid related terms vs number of new covid cases in Mexico

```{r, message=F, comment=F}
#covid case data
library("readr")

covid_data_df<-read.csv("https://covid19.who.int/WHO-COVID-19-global-data.csv") %>%
  filter(Country == "Mexico") %>%
  select(-Country_code,-Country,-WHO_region) %>%
  rename(doc_id = Date_reported)
```

```{r, message=F, comment=F}
#matrix for covid related terms in 2020 and 2021
covid_dic <- dictionary(list(all_terms = c("pandemia", "virus", "crisis", "covid", "sanitaria", "enfermedad")))
dfm_covid <- tokens(subset_president_interim) %>% tokens_select(covid_dic) %>% dfm()

#add date and turn into data.frame
docnames(dfm_covid) <- docvars(dfm_covid, "Date")
covid_terms_df <- convert(dfm_covid, to = "data.frame")
covid_terms_df

covid_terms_df <- covid_terms_df %>% mutate(total_freq = (crisis + enfermedad + virus + sanitaria + pandemia + covid))
final_df <- left_join(covid_terms_df, covid_data_df)
final_df
```

```{r}
coef <- 1000 #value used to transform the data for a second y-axis

ggplot(final_df, aes(x=doc_id)) +
  geom_point( aes(y=total_freq), size=0.2, color = "darkred") + 
  geom_point( aes(y=New_cases / coef), size=0.2, color="steelblue") +
  scale_y_continuous(name = "Frequency of covid related terms", sec.axis = sec_axis(~.*coef, name="Number of new cases")) + 
    labs(title = "President Obrador's Covid Related Remarks vs\nNumber of New Covid Cases in Mexico",
        x = "Date") +
    theme(plot.title = element_text(size = 12, face = "bold", margin = margin(0, 0, 10, 0)),
        plot.subtitle = element_text(size = 10, color = "azure4", margin = margin(0, 0, 10, 0)),
        plot.caption = element_text(size = 7, color = "azure4", vjust = -2),
        axis.title.x = element_text(size = 8, color = "azure4", vjust = -2),
        axis.title.y = element_text(size = 8, color = "azure4" , vjust = 2))
```


